/** Libellés et tonalités de statut — cohérents dans tout l’admin. */

export type StatusTone =
  | "success"
  | "warning"
  | "danger"
  | "neutral"
  | "info";

const TONE_BY_STATUS: Record<string, StatusTone> = {
  ACTIF: "success",
  NORMAL: "success",
  FAIBLE: "warning",
  RUPTURE: "danger",
  ENTREE: "success",
  SORTIE: "info",
  AJUSTEMENT: "warning",
  PERTE: "danger",
  INVENTAIRE: "info",
  RESERVATION: "warning",
  LIBERATION: "neutral",
  VENTE: "success",
  RETOUR: "info",
  DEMANDE: "warning",
  EN_ETUDE: "info",
  PROPOSITION: "info",
  ACCEPTEE: "success",
  EXPIREE: "warning",
  ACTIVE: "success",
  EXPIRED: "warning",
  RELEASED: "neutral",
  CONSUMED: "info",
  PUBLIE: "success",
  PUBLIEE: "success",
  ACTION_PRISE: "success",
  APPROUVEE: "success",
  VALIDE: "success",
  VERIFIE: "success",
  CLOTURE: "neutral",
  EN_ATTENTE: "warning",
  EN_VERIFICATION: "warning",
  VALIDEE: "success",
  PAIEMENT_EN_ATTENTE: "warning",
  PAYEE: "success",
  EN_PREPARATION: "info",
  PRETE: "success",
  EN_LIVRAISON: "info",
  LIVREE: "success",
  RETIRE_DEPOT: "success",
  NON_SOUMIS: "neutral",
  NON_VERIFIE: "neutral",
  VERIFIEE: "success",
  BROUILLON: "warning",
  NOUVEAU: "warning",
  NOUVELLE: "warning",
  PRISE_EN_CHARGE: "info",
  PLANIFIEE: "info",
  TERMINEE: "success",
  ANNULEE: "neutral",
  RESERVATION_EXPIREE: "warning",
  EN_ANALYSE: "warning",
  EN_EXAMEN: "warning",
  SOUMISE: "warning",
  COMPLEMENT_REQUIS: "warning",
  A_CORRIGER: "warning",
  SUSPENDU: "danger",
  SUSPENDUE: "danger",
  BLOQUE: "danger",
  DESACTIVE: "danger",
  INACTIF: "danger",
  REJETE: "danger",
  REJETEE: "danger",
  REFUSEE: "danger",
  REFUSE: "danger",
  SUCCES: "success",
  AUTORISE: "success",
  ECHEC: "danger",
};

const LABEL_BY_STATUS: Record<string, string> = {
  A_CORRIGER: "À CORRIGER",
  ANNULEE: "Annulée",
  RESERVATION_EXPIREE: "Réservation expirée",
  APPROUVEE: "APPROUVÉE",
  ARCHIVE: "ARCHIVÉ",
  BLOQUE: "BLOQUÉ",
  CLOTURE: "CLÔTURÉ",
  COMPLEMENT_REQUIS: "COMPLÉMENT REQUIS",
  DESACTIVE: "DÉSACTIVÉ",
  ECHEC: "ÉCHEC",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRÉE",
  RELEASED: "LIBÉRÉE",
  CONSUMED: "CONSOMMÉE",
  EN_ATTENTE: "En attente",
  EN_VERIFICATION: "En vérification",
  VALIDEE: "Validée",
  PAIEMENT_EN_ATTENTE: "Paiement en attente",
  PAYEE: "Payée",
  EN_PREPARATION: "En préparation",
  PRETE: "Prête",
  EN_LIVRAISON: "En livraison",
  LIVREE: "Livrée",
  RETIRE_DEPOT: "Retrait effectué",
  NON_VERIFIE: "NON VÉRIFIÉ",
  VERIFIEE: "Vérifiée",
  PUBLIE: "PUBLIÉ",
  PUBLIEE: "PUBLIÉE",
  REFUSE: "REFUSÉ",
  REFUSEE: "REFUSÉE",
  REJETE: "REJETÉ",
  REJETEE: "REJETÉE",
  SUCCES: "SUCCÈS",
  TERMINEE: "TERMINÉE",
  TRAITE: "TRAITÉ",
  TRAITEE: "TRAITÉE",
  VERIFIE: "Fournisseur vérifié",
  DEMANDE: "Demande",
  EN_ETUDE: "En étude",
  PROPOSITION: "Proposition",
  ACCEPTEE: "Acceptée",
  EXPIREE: "Expirée",
  RESERVATION: "Réservation",
  LIBERATION: "Libération",
  VENTE: "Vente",
  RETOUR: "Retour",
};

export function formatStatusLabel(status: string) {
  return LABEL_BY_STATUS[status] ?? status.replaceAll("_", " ");
}

export function statusTone(status: string): StatusTone {
  return TONE_BY_STATUS[status] ?? "neutral";
}
