export const publicAgencies = [
  {
    slug: "habitat-conakry",
    name: "Habitat Conakry",
    initials: "HC",
    city: "Conakry",
    address: "Kipé, Ratoma",
    phone: "+224 622 55 88 99",
    email: "contact@habitat-conakry.example",
    verified: true,
    properties: 18,
    ads: 21,
    specialties: ["Résidentiel", "Location", "Vente"],
    description: "Agence immobilière spécialisée dans les biens résidentiels et professionnels à Conakry.",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=86",
  },
  {
    slug: "immo-plus-guinee",
    name: "Immo Plus Guinée",
    initials: "IP",
    city: "Conakry",
    address: "Lambanyi, Ratoma",
    phone: "+224 621 40 22 10",
    email: "contact@immoplus.example",
    verified: true,
    properties: 12,
    ads: 14,
    specialties: ["Terrains", "Maisons", "Conseil"],
    description: "Accompagnement immobilier pour l’achat, la vente et la recherche de terrains.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=86",
  },
  {
    slug: "conakry-habitat",
    name: "Conakry Habitat",
    initials: "CH",
    city: "Conakry",
    address: "Dixinn Centre",
    phone: "+224 625 70 80 90",
    email: "info@conakryhabitat.example",
    verified: true,
    properties: 9,
    ads: 11,
    specialties: ["Appartements", "Bureaux", "Gestion"],
    description: "Sélection de logements, bureaux et accompagnement administratif des dossiers.",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=86",
  },
  {
    slug: "demeures-de-guinee",
    name: "Demeures de Guinée",
    initials: "DG",
    city: "Kindia",
    address: "Centre-ville",
    phone: "+224 620 31 41 51",
    email: "contact@demeures-guinee.example",
    verified: true,
    properties: 7,
    ads: 8,
    specialties: ["Maisons", "Terrains", "Location"],
    description: "Agence locale dédiée aux opportunités immobilières de Kindia et ses environs.",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=86",
  },
];

export const guideItems = [
  { slug: "rechercher-un-bien", title: "Rechercher un bien immobilier", profile: "Public", duration: "4 min", summary: "Utiliser les filtres, le tri et la fiche d’annonce sans compte." },
  { slug: "creer-un-compte", title: "Créer et sécuriser son compte", profile: "Utilisateur", duration: "5 min", summary: "Inscription, vérification et bonnes pratiques de sécurité." },
  { slug: "demander-role", title: "Demander le rôle Propriétaire ou Agence", profile: "Annonceur", duration: "6 min", summary: "Préparer les informations et suivre la validation manuelle." },
  { slug: "publier-annonce", title: "Préparer et soumettre une annonce", profile: "Annonceur", duration: "7 min", summary: "Créer un bien, préparer une annonce et comprendre la modération." },
  { slug: "signaler-contenu", title: "Signaler une annonce problématique", profile: "Tous", duration: "3 min", summary: "Transmettre un signalement utile sans exposer son identité." },
];

export const faqItems = [
  { q: "Faut-il un compte pour consulter les annonces ?", a: "Non. La consultation et la recherche publiques sont accessibles sans compte. Un compte devient utile pour les favoris, les contacts et les espaces personnalisés." },
  { q: "Qui peut publier une annonce ?", a: "La publication est réservée aux comptes dont le rôle Propriétaire ou Agence a été validé. Le statut général du compte doit aussi permettre l’action." },
  { q: "Pourquoi une annonce peut-elle être rejetée ?", a: "Une annonce incomplète, incohérente, trompeuse, dupliquée ou non conforme à la charte peut être refusée avec un motif." },
  { q: "L’adresse exacte du bien est-elle publique ?", a: "Non par défaut. La plateforme doit privilégier une localisation publique approximative et limiter l’accès à l’adresse précise." },
  { q: "Comment signaler une annonce ?", a: "Utilisez la page de signalement ou le bouton prévu sur la fiche. L’identité du déclarant ne doit pas être communiquée à l’annonceur." },
  { q: "Les paiements sont-ils intégrés dans la version 1 ?", a: "Non. La version 1 couvre la recherche, les comptes, les rôles, les biens, les annonces, les favoris, les contacts, la modération et l’administration." },
];
