"use client";
import Link from "next/link";
import {ArrowLeft,CheckCircle2,Save} from "lucide-react";
import {useParams} from "next/navigation";
import {useState} from "react";
import AgencyShell from "@/components/agence/AgencyShell";
import {agencyProperties} from "@/lib/agence/demo-data";
import styles from "./page.module.css";
export default function EditAgencyPropertyPage(){
 const params=useParams<{slug:string}>();const p=agencyProperties.find(x=>x.slug===params.slug)??agencyProperties[0];const [saved,setSaved]=useState(false);const [form,setForm]=useState({title:p.title,client:p.ownerDisplayName,mandateType:p.mandateType,location:p.location,price:String(p.price),area:String(p.area),bedrooms:String(p.bedrooms),bathrooms:String(p.bathrooms),description:p.description});
 return <AgencyShell active="biens" eyebrow="Modification professionnelle" title="Modifier le bien" description="Mettez à jour les informations et le mandat."><Link href={`/agence/biens/${p.slug}`} className={styles.back}><ArrowLeft size={15}/>Retour à la fiche</Link>{saved&&<div className={styles.success}><CheckCircle2 size={17}/>Modifications simulées enregistrées.</div>}<form className={`${styles.card} ${styles.form}`} onSubmit={e=>{e.preventDefault();setSaved(true)}}><div className={styles.grid}><label className={styles.full}>Titre<input value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label>Client associé<input value={form.client} onChange={e=>setForm(v=>({...v,client:e.target.value}))}/></label><label>Mandat<select value={form.mandateType} onChange={e=>setForm(v=>({...v,mandateType:e.target.value}))}><option>EXCLUSIF</option><option>SIMPLE</option><option>INTERNE</option></select></label><label className={styles.full}>Localisation<input value={form.location} onChange={e=>setForm(v=>({...v,location:e.target.value}))}/></label><label>Prix<input type="number" value={form.price} onChange={e=>setForm(v=>({...v,price:e.target.value}))}/></label><label>Surface<input type="number" value={form.area} onChange={e=>setForm(v=>({...v,area:e.target.value}))}/></label><label>Chambres<input type="number" value={form.bedrooms} onChange={e=>setForm(v=>({...v,bedrooms:e.target.value}))}/></label><label>Salles d’eau<input type="number" value={form.bathrooms} onChange={e=>setForm(v=>({...v,bathrooms:e.target.value}))}/></label><label className={styles.full}>Description<textarea rows={8} value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></label></div><div className={styles.footer}><p>Les changements seront contrôlés par l’API.</p><button type="submit"><Save size={16}/>Enregistrer</button></div></form></AgencyShell>
}
